import type { Metadata } from "next";
import { Leckerli_One } from "next/font/google";
import "./globals.css";

const leckerly = Leckerli_One({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leckerly.className} antialiased p-[10dvw]`}
      >
        {children}
      </body>
    </html>
  );
}
